# Generated by Django 4.2.17 on 2025-01-06 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_part_number', models.CharField(max_length=100, verbose_name='廠商料號')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='總數量')),
                ('inventory_quantity', models.PositiveIntegerField(verbose_name='庫存數量')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='創建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerlist.customer', verbose_name='客戶名稱')),
            ],
            options={
                'verbose_name': '庫存',
                'verbose_name_plural': '庫存管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
