# Generated by Django 4.2.17 on 2025-01-03 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='客戶名稱')),
                ('customer_code', models.CharField(max_length=100, unique=True, verbose_name='客戶代碼')),
                ('unified_number', models.CharField(max_length=50, unique=True, verbose_name='統一編號')),
                ('contact_person', models.CharField(max_length=255, verbose_name='聯絡窗口')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='連絡電話')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='創建人')),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
