# Generated by Django 4.2.17 on 2025-01-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerlist', '0002_alter_customer_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='out_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='送貨地'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='連絡電話'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='代碼'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=255, verbose_name='客戶'),
        ),
    ]
